version: "3.7"

services:
  dns-server:
    image: technitium/dns-server:latest
    container_name: technitium-dns
    restart: unless-stopped
    hostname: dns-server
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "5380:5380"   # DNS-over-HTTPS/TLS (اختیاری)
    environment:
      - DNS_SERVER_LOG_USING_LOCAL_TIME=true
      - DNS_SERVER_DOMAIN=dns-server
      - TZ=Europe/Berlin
    volumes:
      - dns_data:/etc/dns/
      
  app:
    image: jc21/nginx-proxy-manager:latest
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    depends_on:
      - db
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm_admin_7q"
      DB_MYSQL_PASSWORD: "jKL3!mNp82@vgTzQ"
      DB_MYSQL_NAME: "npm_db_7q"
    volumes:
      - app_data:/data
      - ./letsencrypt:/etc/letsencrypt

  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: "R!t8bqX#P0mLpZ@k"
      MYSQL_DATABASE: "npm_db_7q"
      MYSQL_USER: "npm_admin_7q"
      MYSQL_PASSWORD: "jKL3!mNp82@vgTzQ"
    volumes:
      - npm_db_data:/var/lib/mysql

volumes:
  dns_data:
  npm_db_data:
  app_data:
  
